FROM python:3.10-slim
WORKDIR /app
COPY pyproject.toml /app/
COPY services /app/services
COPY evaluation /app/evaluation
COPY observability /app/observability
RUN pip install --no-cache-dir -e .[train]
CMD ["python", "-m", "services.training.pretrain.train"]
